baseURL = 'https://luisrego.com/ardeidae-demo/'
languageCode = 'en-us'
title = 'Ardeidae Theme Demo'
theme = 'Ardeidae'

[params]
email="example@email.com"
dateform="2006-01-02"
github = "https://github.com/LuisSousaRego"
